name: ${project.name}
main: ${project.groupId}.${project.artifactId}.${project.name}
version: ${betonquest.version}
description: ${project.description}
website: ${project.organization.url}
author: ${project.organization.name}
authors: [ Wolf2323, SaltyAimbOtter, seyfahni, joblo2213, bundabrg, Co0sh ]
api-version: ${minecraft.api.version}
softdepend:
  - Skript
  - MMOLib
  - MMOCore
  - MMOItems
  - Citizens
  - MythicMobs
  - Vault
  - EffectLib
  - PlayerPoints
  - Heroes
  - Magic
  - Denizen
  - WorldEdit
  - FastAsyncWorldEdit
  - WorldGuard
  - mcMMO
  - Shopkeepers
  - ProSkillAPI
  - Quests
  - PlaceholderAPI
  - HolographicDisplays
  - ProtocolLib
  - Brewery
  - Jobs
  - LuckPerms
  - AureliumSkills
commands:
  betonquest:
    description: General quest command
    usage: /<command>
    permission: betonquest.admin
    aliases: [ q, bq, bquest, bquests, betonquests, quest, quests ]
  journal:
    description: Adds journal to your inventory
    usage: /<command>
    permission: betonquest.journal
    aliases: [ j, bj, bjournal, betonjournal, betonquestjournal ]
  backpack:
    description: Opens quest backpack
    usage: /<command>
    permission: betonquest.backpack
    aliases: [ b, bb, bbackpack, betonbackpack, betonquestbackpack ]
  cancelquest:
    description: Opens the window with quest cancelers
    usage: /<command>
    permission: betonquest.backpack
    aliases: [ bcq, bcancelquest, betoncancelquest, betonquestcancelquest ]
  compass:
    description: Opens the compass menu
    usage: /<command>
    permission: betonquest.backpack
    aliases: [ bc, bcompass, betoncompass, betonquestcompass ]
  questlang:
    description: Changes the language
    usage: /<command> lang
    permission: betonquest.language
    aliases: [ ql ]
permissions:
  betonquest.admin:
    default: op
  betonquest.journal:
    default: true
  betonquest.backpack:
    default: true
  betonquest.conversation:
    default: true
  betonquest.language:
    default: true
libraries:
  - org.apache.maven:maven-artifact:3.8.6
  - org.apache.commons:commons-lang3:3.12.0
  - com.google.guava:guava:31.1-jre
  - commons-io:commons-io:2.11.0
  - org.json:json:20220320
  - net.kyori:adventure-api:4.11.0
  - net.kyori:adventure-platform-bukkit:4.1.2
  - net.kyori:adventure-text-serializer-plain:4.11.0
  - com.cronutils:cron-utils:9.2.0
  - com.zaxxer:HikariCP:5.0.1
