name: "Docs Feedback"
description: "Report unclear documentation."
body:
  - type: input
    attributes:
      label: "Docs Version"
      description: "The version of the documentation this report is about."
      placeholder: 2.3.1
    validations:
      required: true
    id: "version"
  - type: textarea
    attributes:
      label: "Improvement"
      description: "What can be improved?"
    validations:
      required: true
